brapi helper test
agostof/ILCI-NotebookTemplates pull request #9
Opened 2023-09-04 21:33 UTC by bethecon

@agostof Could I test this out in the ILCI sandbox before having @btmonier review? I want to see how it working pulling it in through the BrAPI helper.

2023-09-11 19:13 UTC, agostof requested changes
We need to update the templates based on the changes we discussed.

2023-09-12 17:15 UTC, agostof commented
@btmonier, @bethecon suggested you also take a look at the changes before merging. They looked good to me.

2023-09-12 18:26 UTC, btmonier approved these changes

2023-09-14 16:34 UTC, agostof approved these changes

2023-09-14 16:34 UTC, merged